kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-only-ingress-to-workload
  namespace: a0008
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: aspnetapp
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: app-routing-system
    - podSelector:
        matchLabels:
          app: nginx-internal-0
          app.kubernetes.io/component: ingress-controller