#  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root #  for license information.
#  ------------------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetapp-deployment
  namespace: a0008
  labels:
    app.kubernetes.io/name: aspnetapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: aspnetapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aspnetapp
    spec:
      automountServiceAccountToken: false
      securityContext: {}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - aspnetapp
            topologyKey: "kubernetes.io/hostname"
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - ingress-controller
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: aspnet-webapp-sample
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /Environment
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /Environment
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 10001
          runAsGroup: 3000
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            add:
              - NET_BIND_SERVICE # when running containers as non-root users, if a service within the container needs to listen on a well-known port (e.g., HTTP on port 80, HTTPS on port 443), the NET_BIND_SERVICE capability must be explicitly granted to the container.
            drop:
              - all
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
        env:
        - name: ASPNETCORE_URLS
          value: "http://*:8080"
      nodeSelector:
        agentpool: npuser01
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: aspnetapp-pdb
  namespace: a0008
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: aspnetapp
---
kind: Service
apiVersion: v1
metadata:
  name: aspnetapp-service
  namespace: a0008
spec:
  selector:
    app.kubernetes.io/name: aspnetapp
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
